services:
  - type: web
    name: text-to-sql
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY_1
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: APP_DATABASE_URL
        sync: false
